name: Node.js CI

on:
  push:
    branches: [feat-tests]
  pull_request:
    branches: [feat-tests]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          NODE_AUTH_TOKEN: ${{secrets.GENESIS_SECRET_REP}}
